require("@babel/register")({
  presets: ["@babel/preset-react"],
  plugins: ["transform-es2015-modules-commonjs"]
});

const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CopyWebpackPlugin    = require('copy-webpack-plugin')
const HtmlPlugin           = require("html-webpack-plugin");
const fs                   = require("fs");
const path                 = require("path");
const process              = require("process")
const { load_config }      = require("./config_file")
const { log }              = require ("./log")

const get_html_plugins_for_pages = (plugin_config, dir, subdir) => {
  const files = fs.readdirSync(dir);
  if (!subdir) {
    subdir = "";
  }

  return files.map( (file) => {
    const pathToFile = path.join(dir,file);
    const fileIsDirectory = fs.lstatSync(pathToFile).isDirectory();

    if (fileIsDirectory) {
      const newSubdir = path.join(subdir, path.basename(pathToFile));
      log(`${pathToFile} is a directory; recursing to ${newSubdir}`);
      return get_html_plugins_for_pages(plugin_config,pathToFile,newSubdir);
    }
    else {
      if (path.extname(file) === ".html") {
        log(`${pathToFile} is an html file, creating a plugin`)
        const template = pathToFile;
        const destinationFile = path.join(subdir, file);

        log(`Making plugin: ${template} into ${destinationFile}`)

        return new HtmlPlugin(
          Object.assign(
            plugin_config,
            {
              template: template,
              filename: destinationFile
            }
          )
        );
      }
      else {
        log(`Ignoring ${pathToFile}, since it's not an HTML file`)
      }
    }
  }).flat(1).filter( (element) => {
    return element != null
  });
}

const default_html_plugin_options = (config) => {
  if (config.minify) {
    return {
      minify: {
        "caseSensitive": false,
        "collapseBooleanAttributes": true,
        "collapseInlineTagWhitespace": false,
        "collapseWhitespace": true,
        "conservativeCollapse": true,
        "continueOnParseError": false,
        "decodeEntities": true,
        "html5": true,
        "ignoreCustomFragments": [],
        "includeAutoGeneratedTags": false,
        "keepClosingSlash": false,
        "maxLineLength": 0,
        "minifyCSS": true,
        "minifyJS": true,
        "preserveLineBreaks": false,
        "preventAttributesEscaping": false,
        "processConditionalComments": true,
        "processScripts": [ ],
        "removeAttributeQuotes": false,
        "removeComments": true,
        "removeEmptyAttributes": true,
        "removeEmptyElements": true,
        "removeOptionalTags": false,
        "removeRedundantAttributes": true,
        "removeScriptTypeAttributes": true,
        "removeStyleLinkTypeAttributes": true,
        "removeTagWhitespace": false,
        "sortAttributes": true,
        "sortClassName": true,
        "trimCustomFragments": true,
        "useShortDoctype": true
      }
    }
  }
  else {
    return {};
  }
}

module.exports = function(_) {
  const config = load_config(process.env)

  let plugins = []
  const html_plugins = get_html_plugins_for_pages(default_html_plugin_options(config), config.webpack_input_path)
  const copy_webpack_plugin = new CopyWebpackPlugin(
    [
      { 
        from: config.webpack_input_path,
        to: config.output_path,
        ignore: [
          "*.js",
          "*.css",
          "*.html",
          "components/*"
        ]
      }
    ],
    {
      debug: true
    }
  )
  let filename_for_css = "styles.css"
  if (config.hash) {
    filename_for_css = "styles-[contenthash].css"
  }
  const css_plugin = new MiniCssExtractPlugin({ filename: filename_for_css })

  plugins = plugins.concat(html_plugins)
  plugins = plugins.concat([ copy_webpack_plugin ])
  plugins = plugins.concat([ css_plugin ])

  let filename_for_js_bundle = "bundle.js"
  if (config.hash) {
    filename_for_js_bundle = "bundle-[contenthash].js"
  }

  let optimization = {}
  if (config.minify) {
    optimization.minimize = true
  }

  return {
    module: {
      rules: [
        {
          test: /.css$/,
          use: [
            MiniCssExtractPlugin.loader,
            "css-loader"
          ]
        }
      ]
    },
    plugins: plugins,
    context: config.root,
    entry: `${config.webpack_input_path}/js/index.js`,
    mode: 'none',
    optimization: optimization,
    output: {
      path: config.output_path,
      filename: filename_for_js_bundle
    }
  };
}
